---
title: "Security Policy Forecasting Tournament"
subtitle: "Frequently Asked Questions"
author: ""
output: html_document
---

# Introduction

Welcome to the online glossary of the Security Policy Forecasting Tournament. On this site you find further information which should help you to get a better grasp of the tournament. After the tournament the results and background information regarding the questions will be published on this site. If anything remains unclear, don't hesitate to write an [email](a.sacharow@mpp.hertie-school.org).

# Purpose and aim
Forecasting tournaments are a useful tool to better understand and improve forecasting. They have been extensively used in many future-oriented fields like weather predictions and financial markets. However, only recently they have been introduced to forecasting in international politics. (e.g. [The Good Judgement Project](www.gjopen.com)). The Security Policy Forecasting Tournament is continuing this effort. Its particular goals are to increase awareness of crowd-based forecasting in Europe and to gain further understanding in the relevance of successful forecasting for policy makers. 

# Methodology

## Brier Score

The Brier score was originally proposed to quantify the accuracy of weather forecasts, but can be used to describe the accuracy of any probabilistic forecast. Roughly, the Brier score indicates how far away from the truth your forecast was.

The Brier score is the squared error of a probabilistic forecast. To calculate it, we divide your forecast by 100 so that your probabilities range between 0 (0%) and 1 (100%). Then, we code reality as either 0 (if the event did not happen) or 1 (if the event did happen). For each answer option, we take the difference between your forecast and the correct answer, square the differences, and add them all together. For a yes/no question where you forecasted 70% and the event happened, your score would be (1 – 0.7)2 + (0 – 0.3)2 = 0.18. The best (lowest) possible Brier score is 0, and the worst (highest) possible Brier score is 2.

For further information see [Wikipedia](https://en.wikipedia.org/wiki/Brier_score) or [The Good Judgement Open](https://www.gjopen.com/faq).

## Score Board

The Scoring Board is computed by averaging the brier scores of each participants and ranking them from the lowest to the highes Brier score. As all participants are required to give judgements to all question no gambling by not answering questions is possible.

# Forecasting questions

## Terminology

1. Question:
"Sanctions against Russia" refer to executive orders (13660, 13661, 13662, 13685) of the U.S. president implemented after the 2014 annexation of Crimea by Russia and the hostilities in Eastern Ukraine. "lift or loosen" refers to changes or terminations of these orders which effectly reduce the scope of the sanctions.

2. Question: 
"nuclear weapons test" refers to an event which is mostlikely due to a intented explosion using radioactive explosives.  The resulting quake is usually recorded by non-North Korean geological services (e.g. Federal Institute for Geosciences and Natural Resources, Germany).

3. Question:
"International court or arbitration" is any judicial procedure which is not under national jurisdiction (e.g. International Tribunal for the Law of the Sea (ITLOS)) and usually based on an international treaty (e.g. United Nations Convention on the Law of the Sea (UNCLOS)).

4. Question:
“High-level official representative” refers to the prime-minister, president and minister. For the event to occur an actual face-to-face meeting has to take place in the given time frame. However, it is not required to be a bilateral meeting.

5. Question:
“Operating out of Pakistan” refers to the operational headquarters of the attack. The involvement of individuals from Pakistan has to be reported by international media or outside governments. "Attack" refers to the use of physical violence which has the potential to kill people.

6. Question:
"announce" referes to a statement in an official document (e.g. press release) or public speech. The NATO deployments plans in Eastern Europe are part of the NATO operation Atlantic Resolve.

7. Question:
In the Iran Nuclear Deal (Officially Joint Comprehensive Plan of Action (JCPOA)) the U.S. government agreed to lift sanctions against Iran. “Reintroducing” refers to making these sanctions legal binding again or implementing new sanctions aiming at Iran's Nuclear Program.

8. Question:
"administrative control" referes to the capacity to enforce rules and legislation

9. Question:
"administrative control" referes to the capacity to enforce rules and legislation

10. Question:
The assessment of the Special Inspector General for Afghanistan Reconstruction (SIGAR) will serve as reference.

11. Question:
"FARC splinter group" refers to any group which has or had a relationship with FARC and which split away from FARC in the light of the peace deal.

12. Question:
As reference for the number of deaths serve the statistics published by the International Crisis Group.

13. Question:
All protest before and after the selection of the Hong Kong Chief Executive which takes reference to it is considered. If different counting estimations about the number of participants exist, they are averaged.

14. Question: 
"Claims responsibility" refers to any statement from the organization or a high ranking member attributing the attack them. "Attack" refers to the use of physical violence which has the potential to kill people.

15. Question:
Number of deaths according to official statistics or international media reports.

16. Question: 
Bombing attack refers to any air-to-ground use of force by the Government of Saudi-Arabia.

17. Question:
"announce" referes to a statement in an official document (e.g. press release) or public speech. "No-flight zone" refers to a distinct area were flight are only allowed with permitance of the U.S. government and any violation entails the risk to be shot done. 

18. Question: 
"Hold" means that the involved parties publically endorse the cease-fire.

19. Question: 
"Peace deal"" refers to an agreement which goes beyond a cease-fire and regulates the long-term relation between the involved party and the Syrian government. "Some armed group" refers to any group which was actively fighting in the Syrian Civil War.

20.  Question: 
"deployed U.S. troops" refers to the U.S. non-combar mission with currently 5200 military members advising and assisting local forces.

21. Question: "Casualty" refers to a person killed or injured in a war or accident (Source: Oxford Dictionary). The OHCHR Ukraine report is published [here](http://www.ohchr.org/EN/Countries/ENACARegion/Pages/UAReports.aspx).

22. Question: "Single event" refers to everything which is connect through the same point of time or the source of death. 

23. Question: "Claims responsibility" refers to any statement from the organization or a high ranking member attributing the attack them. "Attack" refers to the use of physical violence which has the potential to kill people.

24. Question: "Suicide attacks" include all attacks where the attacker purposely killed him/herself, attempted to do so or acted as if she/he had the intention to die.